project:
  type: website
  output-dir: docs

website:
  title: "Clara Bowman"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house-door-fill
      - href: interests.qmd
        text: My Interests
        icon: heart-fill

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    smooth-scroll: true
    link-external-newwindow: true

editor: visual
